version: "3.8"
services: 
  php:
    build: ./docker/php
    volumes: 
      - ./laravel_app:/work
  
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel_app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work